// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, public_member_api_docs, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK_X-JccM7MRWlssXkrschO9bGpBRrlCI',
    appId: '1:270481918709:web:160e55db58a3d47b41d3bc',
    messagingSenderId: '270481918709',
    projectId: 'quick-reminders',
    authDomain: 'quick-reminders.firebaseapp.com',
    storageBucket: 'quick-reminders.appspot.com',
    measurementId: 'G-QC4CLDGSVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2o_ASXAtujwltg8ONaxoRLPdkg3Ofy9M',
    appId: '1:270481918709:android:858e25b9f11fd77a41d3bc',
    messagingSenderId: '270481918709',
    projectId: 'quick-reminders',
    storageBucket: 'quick-reminders.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM0IlItqZbazJCx-5qrTXRHM189KtXs1M',
    appId: '1:270481918709:ios:e1740167d075504141d3bc',
    messagingSenderId: '270481918709',
    projectId: 'quick-reminders',
    storageBucket: 'quick-reminders.appspot.com',
    iosClientId: '270481918709-66pt4q8pabmq6qm903qs09v55hsvlerv.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickReminders',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM0IlItqZbazJCx-5qrTXRHM189KtXs1M',
    appId: '1:270481918709:ios:e1740167d075504141d3bc',
    messagingSenderId: '270481918709',
    projectId: 'quick-reminders',
    storageBucket: 'quick-reminders.appspot.com',
    iosClientId: '270481918709-66pt4q8pabmq6qm903qs09v55hsvlerv.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickReminders',
  );
}
